# Generated by Django 4.1.3 on 2022-11-21 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_tag_scope_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ('is_main', 'topic'), 'verbose_name': 'Тематика статьи', 'verbose_name_plural': 'Тематики статьи'},
        ),
    ]
